// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNoZYrIi3grC4NM48beAgkSpYP6c1QOTY',
    appId: '1:242887280631:web:ad4127cc1c87d3548590f2',
    messagingSenderId: '242887280631',
    projectId: 'stock-a0a8c',
    authDomain: 'stock-a0a8c.firebaseapp.com',
    storageBucket: 'stock-a0a8c.firebasestorage.app',
    measurementId: 'G-T0GQEGP712',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXN-HhZy7JLjjLdKtd2E39EYLkkyD5SN0',
    appId: '1:242887280631:android:c04a35020026b7468590f2',
    messagingSenderId: '242887280631',
    projectId: 'stock-a0a8c',
    storageBucket: 'stock-a0a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGvukcjsm_mRwz-eZB-LiFYoH-MeSm2os',
    appId: '1:242887280631:ios:f4a3d58b9d0046488590f2',
    messagingSenderId: '242887280631',
    projectId: 'stock-a0a8c',
    storageBucket: 'stock-a0a8c.firebasestorage.app',
    iosBundleId: 'com.motorstock.stocksimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGvukcjsm_mRwz-eZB-LiFYoH-MeSm2os',
    appId: '1:242887280631:ios:f4a3d58b9d0046488590f2',
    messagingSenderId: '242887280631',
    projectId: 'stock-a0a8c',
    storageBucket: 'stock-a0a8c.firebasestorage.app',
    iosBundleId: 'com.motorstock.stocksimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNoZYrIi3grC4NM48beAgkSpYP6c1QOTY',
    appId: '1:242887280631:web:3db88d5119c177118590f2',
    messagingSenderId: '242887280631',
    projectId: 'stock-a0a8c',
    authDomain: 'stock-a0a8c.firebaseapp.com',
    storageBucket: 'stock-a0a8c.firebasestorage.app',
    measurementId: 'G-0EFWE7M29X',
  );
}
